DROP TABLE IF EXISTS DATAMART_REPORT CASCADE ; 
DROP TABLE IF EXISTS UPLOAD_STATUS CASCADE ;
DROP TABLE IF EXISTS SET_TYPE CASCADE ;
DROP TABLE IF EXISTS SOURCE_MASTER CASCADE ; 
DROP TABLE IF EXISTS SET_UPLOAD_STATUS  CASCADE ;

DROP TABLE IF EXISTS ENCOUNTER_MAPPING CASCADE ; 
DROP TABLE IF EXISTS PATIENT_MAPPING CASCADE ; 
DROP TABLE IF EXISTS CODE_LOOKUP CASCADE ; 
DROP TABLE IF EXISTS CONCEPT_DIMENSION CASCADE ; 
DROP TABLE IF EXISTS OBSERVATION_FACT CASCADE ; 
DROP TABLE IF EXISTS PATIENT_DIMENSION CASCADE ; 
DROP TABLE IF EXISTS PROVIDER_DIMENSION CASCADE ; 
DROP TABLE IF EXISTS VISIT_DIMENSION CASCADE ; 
DROP TABLE IF EXISTS MODIFIER_DIMENSION CASCADE ; 

DROP TABLE IF EXISTS QT_QUERY_MASTER CASCADE ;
DROP TABLE IF EXISTS QT_QUERY_RESULT_TYPE CASCADE ;
DROP TABLE IF EXISTS QT_QUERY_STATUS_TYPE CASCADE ;
DROP TABLE IF EXISTS QT_QUERY_INSTANCE CASCADE ;
DROP TABLE IF EXISTS QT_QUERY_RESULT_INSTANCE CASCADE ;
DROP TABLE IF EXISTS QT_PATIENT_SET_COLLECTION CASCADE ; 
DROP TABLE IF EXISTS QT_PATIENT_ENC_COLLECTION CASCADE ;
DROP TABLE IF EXISTS QT_XML_RESULT CASCADE ;
DROP TABLE IF EXISTS QT_ANALYSIS_PLUGIN CASCADE ;
DROP TABLE IF EXISTS QT_ANALYSIS_PLUGIN_RESULT_TYPE CASCADE ;
DROP TABLE IF EXISTS QT_PRIVILEGE CASCADE ;
DROP TABLE IF EXISTS QT_BREAKDOWN_PATH CASCADE ;
DROP TABLE IF EXISTS QT_PDO_QUERY_MASTER CASCADE ;

DROP TABLE IF EXISTS ARCHIVE_OBSERVATION_FACT CASCADE ;




