DROP TABLE IF EXISTS IM_MPI_DEMOGRAPHICS CASCADE ;
DROP TABLE IF EXISTS IM_MPI_MAPPING CASCADE ;
DROP TABLE IF EXISTS IM_PROJECT_SITES CASCADE ;
DROP TABLE IF EXISTS IM_PROJECT_PATIENTS CASCADE ;
DROP TABLE IF EXISTS IM_AUDIT CASCADE ; 

	