DROP TABLE IF EXISTS ONT_PROCESS_STATUS CASCADE ; 
DROP TABLE IF EXISTS I2B2 CASCADE ;
DROP TABLE IF EXISTS BIRN CASCADE ;
DROP TABLE IF EXISTS SCHEMES CASCADE ;
DROP TABLE IF EXISTS TABLE_ACCESS CASCADE ;
DROP TABLE IF EXISTS CUSTOM_META CASCADE ;